# ifndef LIBFREELICA_CONSTANTS_H
# define LIBFREELICA_CONSTANTS_H

namespace FreeliCa
{	
	enum CommandCode
	{
		POLLING = 0x00,
		REQUEST_SERVICE = 0x02,
		REQUEST_RESPONSE = 0x04,
		READ_WITHOUT_ENCRYPTION = 0x06,
		WRITE_WITHOUT_ENCRYPTION = 0x08,
		SEARCH_SERVICE_CODE = 0x0A,
		REQUEST_SYSTEM_CODE = 0x0C,
		AUTHENTICATION_1 = 0x10,
		AUTHENTICATION_2 = 0x12,
		READ = 0x14,
		WRITE = 0x16,
		REQUEST_SERVICE_V2 = 0x32,
		GET_SYSTEM_STATUS = 0x38,
		REQUEST_SPECIFICATION_VERSION = 0x3C,
		RESET_MODE = 0x3E,
		AUTHENTICATION_1_V2 = 0x40,
		AUTHENTICATION_2_V2 = 0x42,
		READ_V2 = 0x44,
		WRITE_V2 = 0x46,
		UPDATE_RANDOM_ID = 0x4C,

		POLLING_RESPONSE = 0x01,
		REQUEST_SERVICE_RESPONSE = 0x03,
		REQUEST_RESPONSE_RESPONSE = 0x05,
		READ_WITHOUT_ENCRYPTION_RESPONSE = 0x07,
		WRITE_WITHOUT_ENCRYPTION_RESPONSE = 0x09,
		SEARCH_SERVICE_CODE_RESPONSE = 0x0B,
		REQUEST_SYSTEM_CODE_RESPONSE = 0x0D,
		AUTHENTICATION_1_RESPONSE = 0x11,
		AUTHENTICATION_2_RESPONSE = 0x13,
		READ_RESPONSE = 0x15,
		WRITE_RESPONSE = 0x17,
		REQUEST_SERVICE_V2_RESPONSE = 0x33,
		GET_SYSTEM_STATUS_RESPONSE = 0x39,
		REQUEST_SPECIFICATION_VERSION_RESPONSE = 0x3D,
		RESET_MODE_RESPONSE = 0x3F,
		AUTHENTICATION_1_V2_RESPONSE = 0x41,
		AUTHENTICATION_2_V2_RESPONSE = 0x43,
		READ_V2_RESPONSE = 0x45,
		WRITE_V2_RESPONSE = 0x47,
		UPDATE_RANDOM_ID_RESPONSE = 0x4D,
	};

	enum AreaAttribute
	{
		CAN_CREATE_SUBAREA = 0x00,
		CANNOT_CREATE_SUBAREA = 0x01,
	};

	enum ServiceAttribute
	{
		RANDOM_SERVICE_RW_AUTH = 0x08,
		RANDOM_SERVICE_RW_NOAUTH = 0x09,
		RANDOM_SERVICE_RO_AUTH = 0x0A,
		RANDOM_SERVICE_RO_NOAUTH = 0x0B,

		CYCLIC_SERVICE_RW_AUTH = 0x0C,
		CYCLIC_SERVICE_RW_NOAUTH = 0x0D,
		CYCLIC_SERVICE_RO_AUTH = 0x0E,
		CYCLIC_SERVICE_RO_NOAUTH = 0x0F,

		PURSE_SERVICE_DIRECT_AUTH = 0x10,
		PURSE_SERVICE_DIRECT_NOAUTH = 0x11,
		PURSE_SERVICE_CASHBACK_AUTH = 0x12,
		PURSE_SERVICE_CASHBACK_NOAUTH = 0x13,
		PURSE_SERVICE_DECREMENT_AUTH = 0x14,
		PURSE_SERVICE_DECREMENT_NOAUTH = 0x15,
		PURSE_SERVICE_RO_AUTH = 0x16,
		PURSE_SERVICE_RO_NOAUTH = 0x17,
	};

	enum StatusFlag2Value
	{
		SUCCESS = 0x00,
		INVALID_PURSE_CHANGE = 0x01,
		INVALID_CASHBACK = 0x02,
		FATAL_MEMORY_ERROR = 0x70,
		MEMORY_REWRITE_LIMIT_REACHED = 0x71,

		ILLEGAL_SERVICE_NUMBER = 0xA1,
		ILLEGAL_COMMAND_PACKET = 0xA2,
		ILLEGAL_BLOCK_LIST = 0xA3,
		ILLEGAL_SERVICE_TYPE = 0xA4,
		ACCESS_NOT_ALLOWED = 0xA5,
		ILLEGAL_SERVICE_CODE_LIST = 0xA6,
		ILLEGAL_BLOCK_LIST_ACCESS_MODE = 0xA7,
		ILLEGAL_BLOCK_NUMBER = 0xA8,
	};
}

# endif /*LIBFREELICA_CONSTANTS_H*/
